name: CI
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # Pin to a real stable version you use locally (check: flutter --version)
          flutter-version: "3.24.4"
          channel: "stable"
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter pub get (example)
        working-directory: example
        run: flutter pub get

      - name: Format check
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
